/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Seo as PrismaSeo } from "@prisma/client";

export class SeoServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.SeoCountArgs, "select">): Promise<number> {
    return this.prisma.seo.count(args);
  }

  async seos(args: Prisma.SeoFindManyArgs): Promise<PrismaSeo[]> {
    return this.prisma.seo.findMany(args);
  }
  async seo(args: Prisma.SeoFindUniqueArgs): Promise<PrismaSeo | null> {
    return this.prisma.seo.findUnique(args);
  }
  async createSeo(args: Prisma.SeoCreateArgs): Promise<PrismaSeo> {
    return this.prisma.seo.create(args);
  }
  async updateSeo(args: Prisma.SeoUpdateArgs): Promise<PrismaSeo> {
    return this.prisma.seo.update(args);
  }
  async deleteSeo(args: Prisma.SeoDeleteArgs): Promise<PrismaSeo> {
    return this.prisma.seo.delete(args);
  }
}
