/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { BlogArticle } from "./BlogArticle";
import { BlogArticleCountArgs } from "./BlogArticleCountArgs";
import { BlogArticleFindManyArgs } from "./BlogArticleFindManyArgs";
import { BlogArticleFindUniqueArgs } from "./BlogArticleFindUniqueArgs";
import { DeleteBlogArticleArgs } from "./DeleteBlogArticleArgs";
import { BlogArticleService } from "../blogArticle.service";
@graphql.Resolver(() => BlogArticle)
export class BlogArticleResolverBase {
  constructor(protected readonly service: BlogArticleService) {}

  async _blogArticlesMeta(
    @graphql.Args() args: BlogArticleCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [BlogArticle])
  async blogArticles(
    @graphql.Args() args: BlogArticleFindManyArgs
  ): Promise<BlogArticle[]> {
    return this.service.blogArticles(args);
  }

  @graphql.Query(() => BlogArticle, { nullable: true })
  async blogArticle(
    @graphql.Args() args: BlogArticleFindUniqueArgs
  ): Promise<BlogArticle | null> {
    const result = await this.service.blogArticle(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => BlogArticle)
  async deleteBlogArticle(
    @graphql.Args() args: DeleteBlogArticleArgs
  ): Promise<BlogArticle | null> {
    try {
      return await this.service.deleteBlogArticle(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
