/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { StaticPage } from "./StaticPage";
import { StaticPageCountArgs } from "./StaticPageCountArgs";
import { StaticPageFindManyArgs } from "./StaticPageFindManyArgs";
import { StaticPageFindUniqueArgs } from "./StaticPageFindUniqueArgs";
import { DeleteStaticPageArgs } from "./DeleteStaticPageArgs";
import { StaticPageService } from "../staticPage.service";
@graphql.Resolver(() => StaticPage)
export class StaticPageResolverBase {
  constructor(protected readonly service: StaticPageService) {}

  async _staticPagesMeta(
    @graphql.Args() args: StaticPageCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [StaticPage])
  async staticPages(
    @graphql.Args() args: StaticPageFindManyArgs
  ): Promise<StaticPage[]> {
    return this.service.staticPages(args);
  }

  @graphql.Query(() => StaticPage, { nullable: true })
  async staticPage(
    @graphql.Args() args: StaticPageFindUniqueArgs
  ): Promise<StaticPage | null> {
    const result = await this.service.staticPage(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => StaticPage)
  async deleteStaticPage(
    @graphql.Args() args: DeleteStaticPageArgs
  ): Promise<StaticPage | null> {
    try {
      return await this.service.deleteStaticPage(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
