/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PracticeInfo } from "./PracticeInfo";
import { PracticeInfoCountArgs } from "./PracticeInfoCountArgs";
import { PracticeInfoFindManyArgs } from "./PracticeInfoFindManyArgs";
import { PracticeInfoFindUniqueArgs } from "./PracticeInfoFindUniqueArgs";
import { DeletePracticeInfoArgs } from "./DeletePracticeInfoArgs";
import { PracticeInfoService } from "../practiceInfo.service";
@graphql.Resolver(() => PracticeInfo)
export class PracticeInfoResolverBase {
  constructor(protected readonly service: PracticeInfoService) {}

  async _practiceInfosMeta(
    @graphql.Args() args: PracticeInfoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PracticeInfo])
  async practiceInfos(
    @graphql.Args() args: PracticeInfoFindManyArgs
  ): Promise<PracticeInfo[]> {
    return this.service.practiceInfos(args);
  }

  @graphql.Query(() => PracticeInfo, { nullable: true })
  async practiceInfo(
    @graphql.Args() args: PracticeInfoFindUniqueArgs
  ): Promise<PracticeInfo | null> {
    const result = await this.service.practiceInfo(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PracticeInfo)
  async deletePracticeInfo(
    @graphql.Args() args: DeletePracticeInfoArgs
  ): Promise<PracticeInfo | null> {
    try {
      return await this.service.deletePracticeInfo(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
